In [2]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix
import numpy as np
import json

In [5]:
(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
X_train, X_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=42)

In [7]:
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

In [8]:
X_train = X_train.reshape((-1, 28, 28, 1))
X_val = X_val.reshape((-1, 28, 28, 1))
x_test = x_test.reshape((-1, 28, 28, 1))

In [9]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=5, validation_data=(X_val, y_val))


Epoch 1/5


1500/1500 [==============================] - 23s 15ms/step - loss: 0.1610 - accuracy: 0.9513 - val_loss: 0.0690 - val_accuracy: 0.9771
Epoch 2/5
1500/1500 [==============================] - 29s 20ms/step - loss: 0.0502 - accuracy: 0.9843 - val_loss: 0.0479 - val_accuracy: 0.9865
Epoch 3/5
1500/1500 [==============================] - 28s 19ms/step - loss: 0.0348 - accuracy: 0.9893 - val_loss: 0.0410 - val_accuracy: 0.9883
Epoch 4/5
1500/1500 [==============================] - 25s 17ms/step - loss: 0.0268 - accuracy: 0.9917 - val_loss: 0.0455 - val_accuracy: 0.9868
Epoch 5/5
1500/1500 [==============================] - 25s 17ms/step - loss: 0.0214 - accuracy: 0.9930 - val_loss: 0.0387 - val_accuracy: 0.9887


In [10]:
y_pred_probs = model.predict(x_test)
y_pred = np.argmax(y_pred_probs, axis=1)

313/313 [==============================] - 1s 4ms/step


In [11]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
conf_matrix = confusion_matrix(y_test, y_pred)


In [12]:
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.9913
Precision: 0.9913227576515296
Confusion Matrix:
[[ 976    1    1    0    0    0    0    0    1    1]
 [   0 1126    1    2    0    0    0    2    3    1]
 [   1    0 1027    0    0    0    0    4    0    0]
 [   0    0    1 1005    0    2    0    0    2    0]
 [   0    0    0    0  974    0    2    0    0    6]
 [   1    0    0    9    0  878    1    0    1    2]
 [   2    3    0    0    0    2  947    0    4    0]
 [   0    2    4    0    0    0    0 1016    1    5]
 [   0    0    2    0    0    0    0    1  970    1]
 [   0    0    0    2    3    4    1    0    5  994]]
